version: '3.8' # Docker Compose version
services:
  app:
    build: . # Building from the local Dockerfile
    environment:
      - URL
      - TOKEN
    command:
      [
        "./target/release/rusty-dns",
        "--domain=${DOMAIN}",
        "--api-url=${API_URL}",
        "--token=${TOKEN}"
      ]
